apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app
  labels:
    app: products-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
    spec:
      containers:
        - name: products-app
          image: karan1701/products:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
